### ISSUE TITLE
401 Unauthorized request issue

### ISSUE THREAD

**Issue by rayyavu** [SAP-samples/successfactors-cloud-extension-docusign#16]
Dear @jmsrpp and @nnicora,

We are currently in the process of implementing a similar approach in our project. Following the recent update to the Kyma host endpoint, we have duly modified the API rule host name. Concurrently, we've maintained the code structure in line with codes, while adapting the docker image specifics (Docker hub- Public repository - Pulled the image successfully).

Regrettably, upon integration with SuccessFactors, we encountered a "400" error with the event is triggering. Subsequent attempts to access the same URL via Postman resulted in a "401" issue. We would greatly appreciate your expertise and assistance in resolving this matter.

Looking forward to your guidance and support in overcoming these challenges. Kindly find the attached document and below images for your reference.

**Comment by jmsrpp** [comment]
Hi @rayyavu - when using the token in Postman, please assign it to an Authorization header with the value prefixed by Bearer. An HTTP 400 is a bad request, usually indicating the inbound payload doesn't match what the microservice expects. Can you collect any more details from the SuccessFactors message? Typically one or more of those entries are a link to more details.

**Comment by rayyavu** [comment]
Hello @jmsrpp,

As you pointed out, I've utilized the "Bearer" keyword and transmitted the token as a "Bearer" token, but unfortunately, the issue persists.

I made an attempt to retrieve the payload from SuccessFactors Execution Manager and attached it. It appears that only the "Seqnumber," "userId," and "StartDate" are being passed as part of the payload. I've attached the downloaded from SF instance.

**Comment by jmsrpp** [comment]
Hi @rayyavu - despite that, your Postman query is not authenticating properly. I suggest you use the built-in OAuth 2.0 capability to ensure you are able to access the endpoint. You do not need to manually retrieve and set the bearer token if you utilize this:

<img width="893" alt="image" src="https://github.com/SAP-samples/successfactors-cloud-extension-docusign/assets/6976027/026ed7f1-f90c-4d7e-90fd-302fbeae8666">

Bottom line, your SuccessFactors system is authenticating against the Kyma endpoint successfully, but the request body associated with the payload is not what the microservice expects. Please check the pod logs in Kyma:

https://github.com/SAP-samples/successfactors-cloud-extension-docusign/blob/main/src/services/success-factor-service.js

This has debugging and logging that should notify what was wrong with the payload. Please collect the pod/deployment and share them in this issue. I should also point out that both the classic event subscriber and the oauth2 client in Kyma has been deprecated. As such, we will archive this repository by end of year but leave it accessible so that the core parts of the Kyma extension can be leveraged as desired.

**Comment by rayyavu** [comment]
Hello @jmsrpp ,

Sorry for the delay in response. 

Please find a screenshot of logs from pod and deployement. Seems like the execution is stuck inside the Success-factor-service.js file line number 104. 

![image](https://github.com/SAP-samples/successfactors-cloud-extension-docusign/assets/113580355/c6a6b94b-529a-4bc7-b437-90be56360c13)

**Comment by jmsrpp** [comment]
Closing the issue with suggested steps. Open a new one if issue persists, please.
